server:
  port: 80
  context-path: /pipes
spring:
    profiles:
          active: dev
    mvc:
      static-path-pattern: /WEB-INF/static/**
      view:
        prefix: /WEB-INF/
#        suffix: .ftl
    jackson:
      date-format: yyyy-MM-dd HH:mm:ss
##################mybatis#########
#mybatis:
#  mapper-locations: com/diancall/platf/biz/dao/mapper/*Mapper.xml
#  type-aliases-package: com.diancall.platf.biz.entity


#############mybatis-plus ######################
mybatis-plus:
  mapper-locations: classpath*:mappers/**/*.xml
  typeAliasesPackage: com.diancall.biz.entity
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazyLoadingEnabled: true
    multipleResultSetsEnabled: true

logging:
  level:
    com.diancall.biz: debug
    com.diancall.biz.dao.merch: debug
    com.ibatis: debug
  file: logs/platf.log
