cust:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/diancall_cust?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password:

merch:
    datasource:
      url: jdbc:mysql://127.0.0.1:3306/diancall_merch?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
      username: root
      password:

spring:
  profiles: dev