server:
  port: 80
  context-path: /pipes

  spring:
    profiles:
      active: dev
    mvc:
      static-path-pattern:  /static/**
      view:
        prefix: /WEB-INF/views

#############mybatis-plus 配置######################
mybatis-plus:
  mapper-locations: classpath:com.diancall.platf.biz.dao.mapper.*xml
  type-aliases-package: com.diancall.platf.biz.entity
  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true

---
############开发环境############
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/diancallplatf?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Aa123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
---


